### ISSUE TITLE
Спец. символы в пароле

### ISSUE THREAD

**Issue by osipxd** [qexyorg/WebMCR#1]
Долго не удавалось пройти второй шаг установки т.к. не мог подключиться к БД.
Путем долгих мучений выяснилось что проблема в том, что аперсанд в пароле к БД считывался как "&amp".

**Comment by qexyorg** [comment]
Fixed https://github.com/qexyorg/WebMCR/commit/eadc18e1d72f76a0f720e67a4015f95d2bdedfdf
