### ISSUE TITLE
Функция "Пожаловаться"

### ISSUE THREAD

**Issue by andriihorpenko** [qexyorg/WebMCR#14]
На форуме у пользователей есть 2 варианта "публичности профиля" - открытый и закрытый. Так вот, кнопка "Пожаловаться" доступна только для людей с открытым профилем. А вот если нужно пожаловаться на пользователя с закрытым профилем? Естественно я этого сделать не смогу. Поэтому предлагаю внедрить кнопку "Пожаловаться" и к группе пользователей с закрытым профилем.

http://SSMaker.ru/1036286b/

**Comment by qexyorg** [comment]
На каком еще форуме?

**Comment by andriihorpenko** [comment]
Оу, простите, я очень сильно затупил и приписал к Вам форум Xenforo. Ещё раз простите..;(
