### ISSUE TITLE
WebMCR и Denwer

### ISSUE THREAD

**Issue by andriihorpenko** [qexyorg/WebMCR#15]
Ваш движок работает на Denwer? Просто у меня при установке, когда доходит до 3 этапа-белый экран. http://prntscr.com/bx6z4k

**Comment by qexyorg** [comment]
Когда проверял последний раз на денвере, работал. Скорее всего неверно указаны данные от базы.
Какая версия php и mysql?

**Comment by andriihorpenko** [comment]
PHP 5.3, MySQL 5.5

**Comment by andriihorpenko** [comment]
Проблема решена. В Денвере доступен только MySQL. При установке я первый раз выбрал MySQLi и тогда установка прошла дальше. Странно это. Может Вы случайно поменяли местами MySQL и MySQLi?  Или я что-то не понимаю?

**Comment by qexyorg** [comment]
Нет, ничего не менял
