### ISSUE TITLE
Проблема с установкой некоторых модулей

### ISSUE THREAD

**Issue by andriihorpenko** [qexyorg/WebMCR#16]
Я пытаюсь установить модули, но меня встречает ошибка: 404 - Страница не найдена
Залил все файлы из папки upload, и зашел по ссылке /?mode=banlist, /?mode=mailbox, /?mode=altnews,  /mode=refer. Установился успешно только модуль User-System. API также установил.

**Comment by qexyorg** [comment]
Модули для WebMCR от NC22 не работают на WebMCR Reloaded.
Все доступные для Reloaded дополнения можно найти тут - http://webmcr.com/?do=extensions

**Comment by andriihorpenko** [comment]
А Вы их когда-то сможете портировать?

**Comment by qexyorg** [comment]
Да, конечно.
