### ISSUE TITLE
Произошла ошибка добавления администратора

### ISSUE THREAD

**Issue by Dozorov** [qexyorg/WebMCR#18]
Сервер NGINX
PHP 5.6 (Побывал и с php 7.0)
БД: 5.7.17-0ubuntu0.16.04.1
MySQLi модуль для php установлен.
Таблицы все записывает, но администратора добавить не может. Исходники последние.

Add:

Критическая ошибка баз данных. Обратитесь к администрации.Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'new.u.login' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

Беда совсем)

**Comment by andriihorpenko** [comment]
Подтверждаю. Была такая же ошибка. Исправил понижением версии PHP с 7.1 до 7.

**Comment by Dozorov** [comment]
> Я и на 5.6 побывал....

**Comment by qexyorg** [comment]
Когда возникает данная ошибка?

**Comment by overlord-space** [comment]
@qexyorg они скорее всего говорят про установку.
> Таблицы все записывает, но администратора добавить не может. Исходники последние.

**Comment by andriihorpenko** [comment]
Так и есть. Это вроде последний этап установки.

**Comment by qexyorg** [comment]
https://github.com/qexyorg/WebMCR/commit/9521bdd8c7df0789ded4d40b3b594663dc3e61e4
