### ISSUE TITLE
Ошибка 500 из-за htaccess

### ISSUE THREAD

**Issue by osipxd** [qexyorg/WebMCR#2]
Не хочет у меня работать php_flag engine. .htaccess в папе /uploads выдает ошибку 500.

**Comment by qexyorg** [comment]
http://php.net/manual/ru/configuration.changes.php
Это происходит из-за того, что php работает как CGI
Можно просто удалить, но в этом случае за безопасностью того, что загрузят в эту папку, придется следить самостоятельно.

**Comment by osipxd** [comment]
Разобрался с помощью этого http://php.net/manual/ru/configuration.file.per-user.php
