### ISSUE TITLE
Ошибка мониторинга

### ISSUE THREAD

**Issue by mrRaduga** [qexyorg/WebMCR#21]
Привет,

Ловлю такую ошибку: Мониторинг недоступен.
Настроено все по McAPIcaQuery, query на сервере включен, но все таки не работает.

В чем может быть причина?

**Comment by whatdoimakeup** [comment]
То же самое. Хотелось бы найти решение

**Comment by andrewgorpenko** [comment]
Проект уже мёртвый и не поддерживается.

**Comment by qexyorg** [comment]
Список возможных причин:
- Query игрового сервера отключен. Настройте server.properties
- Query/Ping порт игрового сервера закрыт или ограничен через Firewall или средства защиты от ddos атак. Добавьте IP адрес сайта с которого идет запрос в исключения.
- Query/Ping порт указан неверно. Укажите правильный порт.
- Сайт с которого производится мониторинг ограничил исходящие соединения. Обратитесь к хостинг-провайдеру сайта.
- На сайте отключены функции работы с сокетами (fsockopen, socket_create, stream_socket_client). Включите данные функции в php.ini или обратитесь к хостинг-провайдеру
- Данные от игрового сервера указаны неверно
- Соединение между игровым сервером и мониторингом нестабильное или слишком долгое. Настройте стабильное соединение.
