### ISSUE TITLE
Php 7-8, обновления и фиксы

### ISSUE THREAD

**Issue by dayd21git** [qexyorg/WebMCR#23]
Доброго времени суток. Когда будет переход движка на новые версии php и будет ли?
Как скоро можно ожидать фиксы существующих багов?

Дело в том, что ошибка "error", всплывающая в JS над блоком авторизации/профиля из-за онлайна на сайте, всплывает на версиях php 5.2 и далее, но отсутствует на версии 7.4 к примеру. Однако на версии 8.0 движок устанавливаться не хочет, выдавая ошибки сразу же при переходе на домен после залива движка.

То есть на версию 8.0 не сядешь(из-за движка), а 5.2 устарела в принципе. При 7.4 всё работает, но изначально лично я скачивал версию 1.4.1, так как и в голову не пришло, что под зеленой кнопкой на странице скачивания скрывается последний релиз, а не просто заголовок раздела... Не смотря на это, временами пишут о некоторых недоработках в работе скрипта, вы должны быть в курсе.

И хорошо бы выставить хотя бы на вики конкретные "системные требования" под каждую версию движка, ну или как минимум под последний релиз, чтобы не ставить его методом тыка. Я лично не нашел подобной информации.

**Comment by qexyorg** [comment]
Здравствуйте.
Выход обновлений данной версии движка (WebMCR Reloaded) не планируется.
Данная версия является устаревшей и не рекомендуется к использованию. Смотрите в сторону WebMCR 3.

Следите за обновлениями в официальном сообществе WebMCR - https://vk.com/webmcr
