### ISSUE TITLE
Безопасность данных MySQL

### ISSUE THREAD

**Issue by dayd21git** [qexyorg/WebMCR#24]
Мужики, ну как-то не серьезно это... Кто и зачем придумал выводить данные от БД в веб-интерфейсе аккаунта юзера?
Требование админских прав для просмотра данного раздела не отменяет возможности взлома аккаунта на сайте, особенно при выборе хеширования md5 и doublemd5. Объясните может, что я не понял?

**Не рекомендую к использованию данную CMS** из-за соображений безопасности, пока меня(рядового пользователя) не оповестят конструктивно о причине появления данного модуля. Не считаю это безопасным.

[Ссылка на скриншот из последнего релиза](https://day-d.ru/uploads/other/scr0003.jpg)

**Comment by qexyorg** [comment]
Данная версия является устаревшей и не рекомендуется к использованию. Смотрите в сторону WebMCR 3.

Следите за обновлениями в официальном сообществе WebMCR - https://vk.com/webmcr

**Comment by dayd21git** [comment]
Старое барахло, которое не следует использовать, следует выкидывать с открытого доступа в угоду новому продукту.
Плюс ко всему нет никакой информации о требованиях движка, чтобы ознакомиться со списком и найти подходящий хостинг. Или Вы полагаете, что все поголовно используют VDS под сайты? Это еще учитывая, что движок ориентирован на детей. Достаточно заглянуть на ютуб, чтобы убедиться в возрасте основной массы юзеров, которые пытаются делать свои "проекты".

**Comment by dayd21git** [comment]
> Данная версия является устаревшей и не рекомендуется к использованию. Смотрите в сторону WebMCR 3.
> 
> Следите за обновлениями в официальном сообществе WebMCR - https://vk.com/webmcr

Старое барахло, которое не следует использовать, следует выкидывать с открытого доступа в угоду новому продукту.
Плюс ко всему нет никакой информации о требованиях движка, чтобы ознакомиться со списком и найти подходящий хостинг. Или Вы полагаете, что все поголовно используют VDS под сайты? Это еще учитывая, что движок ориентирован на детей. Достаточно заглянуть на ютуб, чтобы убедиться в возрасте основной массы юзеров, которые пытаются делать свои "проекты".

Не удивительно, что на него нет спроса при такой информативности вики и наличии версий с багами в общем доступе на странице скачивания **релизов**.
