### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by osipxd** [qexyorg/WebMCR#3]
Опечатка в письме при регистрации

![](http://i.imgur.com/aLDAz4l.png)

**Comment by osipxd** [comment]
И сразу сюда же напишу.
Если на каком-то шаге установки что-то введено неверно, то все введенные данные сбрасываются. Хотелось бы чтобы не приходилось по многу раз вводить одно и то же.

**Comment by qexyorg** [comment]
Спасибо. Опечатка исправлена.
По поводу сохранения полей. Уже есть в планах, но пока не хватает на всё времени.
