### ISSUE TITLE
Управление пользователями(WebMCR Reloaded)

### ISSUE THREAD

**Issue by andriihorpenko** [qexyorg/WebMCR#5]
1.В WebMCR 2.4 была строка поиска игрока по нику.(она помогало обнаружить мультаккаунты(по IP)) Есть ли в планах добавление поиска пользователей в новой версии WebMCR? http://SSMaker.ru/bc392e28/
2.Как добавить колонку IP в {{категория: пользователи}{пункт: управление пользователями}} (http://SSMaker.ru/3179c2ba/)?

**Comment by qexyorg** [comment]
Извиняюсь за столь долгий ответ, почему-то оповещения не приходили.
1. Есть в планах.
2. GitHub не дает вставить одинарные кавычки, напишите на почту admin@qexy.org
