### ISSUE TITLE
Привилегии(WebMCR Reloaded)

### ISSUE THREAD

**Issue by andriihorpenko** [qexyorg/WebMCR#6]
Можете добавить привилегию: "Действие над.."(http://SSMaker.ru/aadf68b2/)? Например, есть группа модератор и я не хочу, чтобы участники этой группы имели возможность редактировать профиль игрока. Или хотя бы ограничить доступ к элементам этой функции. То есть,к примеру, оставить "забанить" и "разбанить" а создание, редактирование и удаления профайла-убрать.

**Comment by qexyorg** [comment]
Добавим
